# =============================================================================
# Dispute Agents — Placeholder Logic
# =============================================================================
# This module contains the "brains" that will eventually call a real LLM
# (Large Language Model) API to generate arguments and rulings.
# For now every function returns hard-coded placeholder text so the UI can be
# built and tested without needing an API key or internet connection.
# =============================================================================

import json
import os

import google.generativeai as genai


def call_gemini(prompt_text: str) -> str:
    """
    Send a prompt to the Gemini API and return the generated text.

    Parameters
    ----------
    prompt_text : str
        The full prompt to send to the model.

    Returns
    -------
    str
        The model's response text, or an "[ERROR]" string if the call fails.
    """
    try:
        # Read the API key from the environment variable loaded by dotenv in app.py.
        api_key = os.environ["GEMINI_API_KEY"]

        # Configure the Gemini client with our API key.
        genai.configure(api_key=api_key)

        # Create a model instance.  "gemini-2.0-flash" is a fast, capable model.
        model = genai.GenerativeModel("gemini-2.0-flash")

        # Send the prompt and get the response.
        response = model.generate_content(prompt_text)

        # Return the text content of the first candidate.
        return response.text
    except Exception as exc:
        # If anything goes wrong (network issue, bad key, etc.) return a safe
        # error string instead of crashing the whole Streamlit app.
        return f"[ERROR] Gemini API call failed: {exc}"


def rider_advocate(dispute_data: dict) -> str:
    """
    Build the rider's side of the case using a real LLM call.

    This function:
      1. Formats all available evidence into a clear, structured prompt.
      2. Asks the model to act as the rider's advocate.
      3. Calls call_gemini() and returns the generated argument.

    Parameters
    ----------
    dispute_data : dict
        The full dispute dictionary from sample_disputes.py.

    Returns
    -------
    str
        The AI-generated argument for the rider, or an error message.
    """
    # -------------------------------------------------------------------------
    # Build the evidence block dynamically.
    # We convert the evidence dict to a pretty-printed JSON string so the
    # model can read every field regardless of dispute type (Route Deviation,
    # No-Show Charge, etc.).
    # -------------------------------------------------------------------------
    evidence_json = json.dumps(dispute_data["evidence"], indent=2)

    # -------------------------------------------------------------------------
    # Compose the full prompt.
    # We explicitly tell the model:
    #   - Its role (advocate for the rider).
    #   - What data it has access to.
    #   - The constraint: use ONLY the evidence provided; do not invent facts.
    # This keeps the output grounded in the sample data.
    # -------------------------------------------------------------------------
    prompt = f"""You are an advocate representing the rider in a ride-hailing dispute.

Your job is to build the strongest fair case for the rider using ONLY the evidence provided below. Do NOT invent facts, assume details not in the data, or hallucinate information.

--- RIDER COMPLAINT ---
{dispute_data['rider_complaint']}

--- EVIDENCE ---
{evidence_json}

--- RIDER HISTORY ---
Prior disputes: {dispute_data['rider_profile']['prior_disputes']}

Instructions:
1. State the rider's core grievance clearly.
2. Highlight specific evidence that supports the rider's position.
3. Keep the tone professional and factual.
4. Do not mention that you are an AI.
"""

    return call_gemini(prompt)


def driver_advocate(dispute_data: dict) -> str:
    """
    Build the driver's side of the case.

    In the future this function will call a real AI model to generate a
    counter-argument based on the same evidence.

    Parameters
    ----------
    dispute_data : dict
        The full dispute dictionary from sample_disputes.py.

    Returns
    -------
    str
        Placeholder text representing the driver's argument.
    """
    return "[PLACEHOLDER] Driver Advocate case would appear here."


def judge_ruling(rider_case: str, driver_case: str, dispute_data: dict) -> dict:
    """
    Produce a final ruling after hearing both sides.

    In the future this function will:
      1. Feed the rider_case and driver_case into an LLM judge prompt.
      2. Parse the model's JSON or structured response.
      3. Return a real decision, confidence score, and explanation.

    Parameters
    ----------
    rider_case : str
        The argument generated by rider_advocate().
    driver_case : str
        The argument generated by driver_advocate().
    dispute_data : dict
        The full dispute dictionary (gives the judge access to raw evidence).

    Returns
    -------
    dict
        Placeholder ruling with keys:
        - "decision"     : str
        - "confidence"   : str
        - "explanation"  : str
    """
    return {
        "decision": "[PLACEHOLDER] Decision would appear here.",
        "confidence": "[PLACEHOLDER] Confidence would appear here.",
        "explanation": "[PLACEHOLDER] Explanation would appear here.",
    }
