# =============================================================================
# Dispute Agents — Placeholder Logic
# =============================================================================
# This module contains the "brains" that will eventually call a real LLM
# (Large Language Model) API to generate arguments and rulings.
# For now every function returns hard-coded placeholder text so the UI can be
# built and tested without needing an API key or internet connection.
# =============================================================================


def rider_advocate(dispute_data: dict) -> str:
    """
    Build the rider's side of the case.

    In the future this function will:
      1. Format the evidence into a prompt.
      2. Send the prompt to an LLM API (e.g. OpenAI, Anthropic, local model).
      3. Return the generated argument text.

    Parameters
    ----------
    dispute_data : dict
        The full dispute dictionary from sample_disputes.py.

    Returns
    -------
    str
        Placeholder text representing the rider's argument.
    """
    return "[PLACEHOLDER] Rider Advocate case would appear here."


def driver_advocate(dispute_data: dict) -> str:
    """
    Build the driver's side of the case.

    In the future this function will call a real AI model to generate a
    counter-argument based on the same evidence.

    Parameters
    ----------
    dispute_data : dict
        The full dispute dictionary from sample_disputes.py.

    Returns
    -------
    str
        Placeholder text representing the driver's argument.
    """
    return "[PLACEHOLDER] Driver Advocate case would appear here."


def judge_ruling(rider_case: str, driver_case: str, dispute_data: dict) -> dict:
    """
    Produce a final ruling after hearing both sides.

    In the future this function will:
      1. Feed the rider_case and driver_case into an LLM judge prompt.
      2. Parse the model's JSON or structured response.
      3. Return a real decision, confidence score, and explanation.

    Parameters
    ----------
    rider_case : str
        The argument generated by rider_advocate().
    driver_case : str
        The argument generated by driver_advocate().
    dispute_data : dict
        The full dispute dictionary (gives the judge access to raw evidence).

    Returns
    -------
    dict
        Placeholder ruling with keys:
        - "decision"     : str
        - "confidence"   : str
        - "explanation"  : str
    """
    return {
        "decision": "[PLACEHOLDER] Decision would appear here.",
        "confidence": "[PLACEHOLDER] Confidence would appear here.",
        "explanation": "[PLACEHOLDER] Explanation would appear here.",
    }
